### ISSUE TITLE
网页版的怎么切换卷数?

### ISSUE THREAD

**Issue by k79e** [MrMYHuang/cbetar2#1]
https://mrmyhuang.github.io/catalog/juan/T0220/1
翻到最后就不知道该咋办了 我该怎么查看卷2呢?

**Comment by MrMYHuang** [comment]
> https://mrmyhuang.github.io/catalog/juan/T0220/1
> 翻到最后就不知道该咋办了 我该怎么查看卷2呢?

您好，請使用"回經目錄"功能：
![image](https://user-images.githubusercontent.com/12458706/108156351-7a02ed80-711b-11eb-9e58-d5e1bbf107e4.png)

**Comment by k79e** [comment]
这样也太不方便了.... 建议加个前后切换卷的按钮

**Comment by MrMYHuang** [comment]
> 这样也太不方便了.... 建议加个前后切换卷的按钮

PWA 4.27.0 支援切換卷的按鈕，請重啟 app 1 次，以取得最新 app：
![image](https://user-images.githubusercontent.com/12458706/159876459-d7c5962f-59c2-4472-ae0e-503b0f7f8431.png)
謝謝您的建議。
